CREATE  TABLE LOAN_ACCOUNTS
(
accno CHAR(4),
Cust_name VARCHAR(15),
Loan_Amount DECIMAL(10,2),
Installments INT,
Int_rate DECIMAL(10,2),
Start_date DATE,
Interest DECIMAL(10,2)
);
DESCRIBE LOAN_ACCOUNTS;

ALTER TABLE LOAN_ACCOUNTS
ADD COLUMN category VARCHAR(15);

DESCRIBE LOAN_ACCOUNTS;

INSERT INTO LOAN_ACCOUNTS(accno,Cust_name,Loan_Amount,Installments,Int_rate,Start_date) VALUES(1001,'R.k gupta',300000.00,36,12.00,'2009-07-19'),
(1002,'S.P Sharma',500000.00,48,10.00,'2008-03-22'),
(1003,'K.P Jain',300000.00,36,NULL,'2007-08-03'),
(1004,'M.P Yadav',800000.00,60,10.00,'2008-07-12'),
(1005,'S.P  Sinha',200000.00,36,12.50,'2010-03-01'),
(1006,'P.Sharma',700000.00,60,12.50,'2008-05-06'),
(1007,'K.S Dhall',500000.00,48,NULL,'2008--05-03');

SELECT * FROM LOAN_ACCOUNTS;

UPDATE LOAN_ACCOUNTS
SET Int_rate=11.50 WHERE Accno=1003;

UPDATE LOAN_ACCOUNTS
SET Int_rate=11.50 WHERE Accno=1007;

SELECT * FROM LOAN_ACCOUNTS;

UPDATE LOAN_ACCOUNTS SET INT_RATE=11.50 WHERE Int_rate IS NULL;

UPDATE LOAN_ACCOUNTS SET Int_rate=Int_rate + 0.5 WHERE Loan_Amount > 400000;

SELECT * FROM LOAN_ACCOUNTS;

UPDATE LOAN_ACCOUNTS SET Interest=(Loan_Amount * Int_rate * Installments)/(12*100);

SELECT * FROM LOAN_ACCOUNTS;

DELETE  FROM LOAN_ACCOUNTS WHERE Start_date < '2008-01-01';
SELECT * FROM LOAN_ACCOUNTS;

DELETE FROM LOAN_ACCOUNTS WHERE Cust_name like 'K%';
SELECT * FROM LOAN_ACCOUNTS;

SELECT * FROM LOAN_ACCOUNTS WHERE Installments < 40;

SELECT Int_rate FROM LOAN_ACCOUNTS WHERE Start_date >2009-04-01;

SELECT accno,Loan_Amount FROM LOAN_ACCOUNTS  WHERE Start_date < '2009-04-01';

SELECT accno,Cust_name,Loan_Amount FROM LOAN_ACCOUNTS WHERE CUST_NAME like '%SHARMA';

SELECT Loan_Amount  FROM LOAN_ACCOUNTS WHERE Cust_name like '%a';

SELECT accno,Cust_name,Loan_Amount FROM LOAN_ACCOUNTS WHERE Cust_name   LIKE '%a%';

SELECT accno,Cust_name,Loan_Amount FROM LOAN_ACCOUNTS WHERE NOT(Cust_name  LIKE '%P%');

DESCRIBE LOAN_ACCOUNTS;

SELECT * FROM LOAN_ACCOUNTS ORDER BY  Loan_Amount ASC;

SELECT * FROM LOAN_ACCOUNTS ORDER BY  Start_date DESC;

SELECT * FROM LOAN_ACCOUNTS ORDER BY Loan_Amount,Start_date DESC;

SELECT accno,Cust_name,Loan_Amount FROM LOAN_ACCOUNTS WHERE Cust_name LIKE 'K%';

SELECT * FROM LOAN_ACCOUNTS WHERE Int_rate IS NULL;

SELECT * FROM LOAN_ACCOUNTS WHERE Int_rate is NOT NULL;

SELECT DISTINCT Loan_Amount FROM LOAN_ACCOUNTS ;

SELECT * FROM LOAN_ACCOUNTS WHERE Start_date>2008-12-31 AND  Installments>36;

SELECT Cust_name,Loan_Amount FROM LOAN_ACCOUNTS WHERE Loan_Amount<500000 OR Int_rate>12;

SELECT * FROM LOAN_ACCOUNTS WHERE year(Start_date)='2009';

SELECT * FROM LOAN_ACCOUNTS WHERE Loan_Amount  BETWEEN 400000 AND  500000;

SELECT Cust_name,Loan_Amount  FROM LOAN_ACCOUNTS WHERE Installments IN(26,36,48);

SELECT Cust_name,Loan_Amount ,Int_rate,
CASE WHEN Int_rate IS NULL THEN '0' ELSE Int_rate END FROM LOAN_ACCOUNTS;

SELECT Cust_name,Loan_Amount,Int_rate,
 CASE WHEN Int_rate  IS NULL THEN 'No Interest' ELSE Int_rate END FROM LOAN_ACCOUNTS;






